ClashBet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Main.app_urls')),
    url(r'^', include('Registration.app_urls')),
    url(r'^', include('LK.app_urls')),
    url(r'^', include('Bets.app_urls')),
    url(r'^', include('Offers.app_urls')),
    url(r'^password_reset/$',
        PasswordResetView.as_view(
            template_name='registration/password_reset/password_reset_form.html',
            email_template_name='registration/password_reset/password_reset_email.html',
            subject_template_name='registration/password_reset/password_reset_subject.txt'
        ), name='password_reset'),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(
            template_name='registration/password_reset/password_reset_done.html'
        ), name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(
            template_name='registration/password_reset/password_reset_confirm.html',
        ), name='password_reset_confirm'),
    url(r'^password_reset/complete/$',
        PasswordResetCompleteView.as_view(
            template_name='registration/password_reset/password_reset_complete.html',
        ), name='password_reset_complete'),
]

Bets/models.py
from django.db import models

from Registration.models import Player, Clan


class Bet(models.Model):
    cost = models.FloatField()
    ongoing = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)
    unfinished = models.BooleanField(default=False)
    expiration = models.DateTimeField()
    acception_timestamp = models.BigIntegerField(default=0)
    expiration_timestamp = models.BigIntegerField(default=0)
    time_left = models.IntegerField(default=0)
    time = models.IntegerField(default=300)
    expiration_ongoing_timestamp = models.BigIntegerField(default=0)
    player = models.ForeignKey(Player, default=1, on_delete=models.CASCADE, related_name='player')
    opponent = models.ForeignKey(Player, default=1, on_delete=models.CASCADE, related_name='opponent')
    winner = models.ForeignKey(Player, default=1, on_delete=models.CASCADE, related_name='winner')
    clan = models.ForeignKey(Clan, default=1, on_delete=models.CASCADE, related_name='clan')

    def __str__(self):
        return str(self.id) + ' ' + self.player.user.username + ' ' + str(self.cost)


class ExpiredBet(models.Model):
    bet_id = models.IntegerField(default=0)
    cost = models.FloatField()
    player = models.ForeignKey(Player, default=1, on_delete=models.CASCADE, related_name='eb_player')
    clan = models.ForeignKey(Clan, default=1, on_delete=models.CASCADE, related_name='eb_clan')
    expiration_timestamp = models.BigIntegerField(default=0)

    def __str__(self):
        return str(self.bet_id) + ' ' + self.player.user.username + ' ' + str(self.cost)


class UploadedFile(models.Model):
    name = models.CharField(max_length=200, default='')
    file = models.FileField(upload_to='media/')

    def __str__(self):
        return self.name


class Appeal(models.Model):
    bet = models.ForeignKey(Bet, default=1, on_delete=models.CASCADE)
    reason = models.CharField(max_length=200, default='')
    text = models.TextField(max_length=5000, default='')
    files = models.ManyToManyField(UploadedFile, default=None)

    def __str__(self):
        return self.reason + ' | ' + self.text[:30] + '...'


class BiggestWin(models.Model):
    is_none = models.BooleanField(default=True)
    player = models.ForeignKey(Player, default=1, on_delete=models.CASCADE)
    win_amount = models.FloatField(default=0.0)
    date = models.DateField()

    def __str__(self):
        return self.player.user.username + ' | ' + str(self.win_amount)

Bets/views.py
import datetime
import time as timestamp

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

from Bets.models import Bet, ExpiredBet, Appeal, UploadedFile, BiggestWin
from Main.models import Notification
from Registration.models import Player, Clan

duel_rooms = dict()


def add_duel_room(bet_id, duel_room):
    duel_rooms[bet_id] = duel_room


def get_duel_rooms():
    return duel_rooms


def delete_bets():
    expired_bets = Bet.objects.filter(expiration__lt=datetime.datetime.now(), ongoing=False)
    for bet in expired_bets:
        ExpiredBet.objects.create(
            cost=bet.cost,
            player=bet.player,
            clan=bet.clan,
            expiration_timestamp=bet.expiration_timestamp)
        bet.player.balance += bet.cost
        bet.player.save()
        bet.delete()


def update_biggest_win():
    b_w = BiggestWin.objects.get(id=1)
    curr_date = datetime.datetime.now().date()
    if b_w.date != curr_date:
        b_w.date = curr_date
        b_w.is_none = True
        b_w.save()


@login_required(login_url='/startpage/')
def main(request):
    delete_bets()
    update_biggest_win()
    player = Player.objects.get(user=request.user)
    biggest_win = BiggestWin.objects.get(id=1)
    bets = Bet.objects.filter(finished=False).order_by('cost')
    notifications = Notification.objects.filter(player=player)
    for bet in bets:
        bet.time_left = bet.expiration_timestamp - round(timestamp.time())
        bet.save()
    try:
        bet = Bet.objects.get(player=player, finished=False)
        if bet.ongoing:
            return redirect('/duel/' + str(bet.id))
        else:
            return redirect('/waiting/' + str(bet.id))
    except Bet.DoesNotExist:
        pass
        return render(request, 'main/main.html',
                      {
                          'server_time': timestamp.time(),
                          'player': player,
                          'bets': bets,
                          'biggest_win': biggest_win,
                          'notifications': notifications
                      })


@login_required(login_url='/startpage/')
def make_a_bet(request):
    player = Player.objects.get(user=request.user)
    if request.method == 'POST':

        cost, time = None, None
        try:
            cost = float(request.POST.get('sum', None))
            time = int(request.POST.get('time', None)) * 60
            if cost > player.balance:
                Notification.objects.create(player=player, type='error', text='Ошибка - недостаточно средств')
            if not 300 <= time <= 1800:
                Notification.objects.create(player=player, type='error', text='Ошибка - неверно указано время')
            if cost < 10:
                Notification.objects.create(player=player, type='error',
                                            text='Ошибка - неверно указана стоимость')
            if len(list(Bet.objects.filter(player=player, finished=False))) > 0:
                Notification.objects.create(player=player, type='error',
                                            text='Ошибка - у вас уже есть незавершённые ставки')
        except ValueError:
            Notification.objects.create(player=player, type='error',
                                        text='Ошибка - неверно указаны время или стоимость')

        if len(Notification.objects.filter(player=player, type='error')) == 0:
            expiration_time = timestamp.time() + time
            clan = Clan.objects.get(id=1)
            bet = Bet.objects.create(
                cost=cost,
                time=time,
                expiration=datetime.datetime.utcfromtimestamp(expiration_time),
                expiration_timestamp=expiration_time,
                opponent=player,
                player=player,
                winner=player,
                clan=clan
            )
            player.balance -= cost
            player.save()

            return redirect('/waiting/' + str(bet.id))

    return redirect('/')


@login_required(login_url='/startpage/')
def waiting(request, bet_id):
    player = Player.objects.get(user__username=request.user.username)
    try:
        bet = Bet.objects.get(id=bet_id)
        bet.time_left = bet.expiration_timestamp - round(timestamp.time())
        bet.save()
        if request.user == bet.player.user:
            return render(request, 'bets/waiting.html', {'bet': bet})
        else:
            return redirect('/')
    except Bet.DoesNotExist:
        Notification.objects.create(player=player,
                                    text='Cтавки, которую Вы попытались открыть, не существует',
                                    type='error')
        return redirect('/')


def get_bet_info(request, bet_id):
    delete_bets()
    bet = Bet.objects.get(id=bet_id)
    response = {
        'id': bet_id,
        'username': bet.player.user.username,
        'cost': bet.cost,
        'time': bet.time,
        'time_left': bet.time_left,
        'ongoing': bet.ongoing,
        'opponent': bet.opponent.user.username,
    }
    return JsonResponse(response)


@login_required(login_url='/startpage/')
def duel(request, bet_id):
    player = Player.objects.get(user__username=request.user.username)
    try:
        bet = Bet.objects.get(id=bet_id)
    except Bet.DoesNotExist:
        return redirect('/')
    if request.user.username != duel_rooms[bet_id].duel_player.player.user.username \
            and request.user.username != duel_rooms[bet_id].duel_opponent.player.user.username:
        return redirect('/')
    if bet.player.user.username != request.user.username and not bet.ongoing:
        opponent = Player.objects.get(user=request.user)
        if opponent.balance >= bet.cost:
            opponent.balance -= bet.cost
        else:
            Notification.objects.create(player=player, type='error',
                                        text='Ошибка - у вас недостаточно средств, чтобы принять эту ставку')
            return redirect('/')
    bet.acception_timestamp = round(timestamp.time())
    bet.save()
    comission = 1 if bet.acception_timestamp < player.no_comission_bonus_expiration_timestamp \
        or player.daily_offer_activated else 0.9
    profit = bet.cost * 2 * comission
    checked = None
    try:
        duel_room = duel_rooms[bet_id]
        checked = duel_room.results_correct()
    except KeyError:
        pass
    return render(request, 'bets/duel.html', {'bet': bet, 'profit': profit, 'checked': checked})


def get_battle_status(request):
    bet_id = request.GET.get('bet_id', None)
    response = None
    try:
        bet = Bet.objects.get(id=bet_id)
        if bet.ongoing:
            response = {'battle_status': 'ongoing'}
        elif bet.unfinished:
            response = {'battle_status': 'time_over'}
        else:
            response = {'battle_status': 'not_started'}
    except Bet.DoesNotExist:
        pass
    return JsonResponse(response)


@login_required(login_url='/startpage/')
def appeal(request, bet_id):
    player = Player.objects.get(user__username=request.user.username)
    try:
        bet = Bet.objects.get(id=bet_id)
    except Bet.DoesNotExist:
        Notification.objects.create(player=player, type='error', text='Ошибка - данной ставки не существует')
        return redirect('/')

    if request.method == 'GET':
        player = Player.objects.get(user__username=request.user.username)
        return render(request, 'bets/appeal.html', {'player': player})
    else:
        reason = request.POST.get('reason', None)
        text = request.POST.get('comment', None)
        new_appeal = Appeal.objects.create(bet=bet, reason=reason, text=text)
        files = request.FILES.getlist('files')
        for file in files:
            suffix = str(timestamp.time())
            temp_file = UploadedFile.objects.create(name=file.name + suffix, file=file)
            new_appeal.files.add(temp_file)
        new_appeal.save()
        return redirect('/')


def remove_notification(request, notification_id):
    response = dict()
    try:
        notification = Notification.objects.get(id=notification_id)
        notification.delete()
        response['status'] = 'OK'
    except Notification.DoesNotExist:
        response['status'] = 'ERROR'
    return JsonResponse(response)

templates/bets/appeal.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Апелляция
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/appeal.css" %}">
{% endblock %}
{% block content %}
{% include 'includes/header.html' %}
<div class="container col-xl-4 col-md-6">
    <div class="login-form">
        <div class="card">
            <div class="card-body">
                    <span class="card-title">
                        Апелляция
                    </span>
                <form enctype="multipart/form-data" method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_reason">Причина:</label>
                        <input type="text" name="reason" maxlength="100" autofocus required
                               id="id_reason" placeholder='Например, "Мой противник не принял бой"'
                               class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_comment">Пояснение:</label>
                        <textarea id="id_comment" name="comment" class="form-control" rows="5" cols="50"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_files">Прикрепить файлы:</label>
                        <input type="file" name="files" id="id_files" class="form-control" multiple>
                    </div>
                    <div class="row">
                        <div class="col-12" style="display: flex">
                            <button type="submit" class="btn btn-outline-light col-5">Отправить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

templates/bets/duel.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Дуэль
{% endblock %}
{% block css %}
    {% if player.background %}
        <link rel="stylesheet" href="{% static "css/background.css" %}">{% endif %}
    <link rel="stylesheet" href="{% static 'css/duel.css' %}">
{% endblock %}
{% block content %}
    {% if player.background %}
        <canvas id="background"></canvas>{% endif %}
    <div class="content">
        <div class="container col-xl-4 col-md-6">
            <div class="card">
                <div class="card-body">
                    <div class="players text-center mb-3">
                        {{ bet.player.CRnickname }}<br>
                        <span class="vs"><span id="V">V</span><span id="S">S</span></span><br>
                        {{ bet.opponent.CRnickname }}
                    </div>
                    На кону: {{ profit }} <i class="fas fa-coins"></i><br>
                    Клан: {{ bet.clan.name }} (#{{ bet.clan.hashtag }})<br>
                    Время на битву: <span id="timer" data-expiration-timestamp="{{ bet.expiration_ongoing_timestamp }}"
                                          data-bet-id="{{ bet.id }}">&ndash;&ndash;:&ndash;&ndash;</span>
                    <div id="info" class="duel-info mt-2" data-checked="{{ checked }}">
                        {% if checked is False %}
                            Опаньки!<br>
                            Один из игроков ввёл некорректные данные.<br>
                            Запущена автоматическая проверка результатов...
                        {% else %}
                            <i class="fas fa-info-circle"></i> У вас есть 15 минут чтобы сыграть бой в указанном клане.<br>
                        Как только бой будет сыгран, наша система автоматически определит победителя.<br>
                        В случае ничьи таймер обновится и у вас будет ещё 15 минут на следующий бой.<br>
                        Если по истечении этого времени по каким либо причинам бой не будет сыгран, вы сможете подать на
                        апелляцию.
                        {% endif %}
                    </div>
                    <div id="result" class="d-none mt-4">
                        <div class="mb-2">
                            Результат боя:
                        </div>
                        <input id="id_win" type="radio" name="result" checked>
                        <label for="id_win">я выиграл</label>
                        <input id="id_lose" type="radio" name="result">
                        <label for="id_lose">я проиграл</label>
                        <input id="id_draw" type="radio" name="result">
                        <label for="id_draw" class="m-0">ничья</label>
                        <button class="btn offset-sm-8" id="send-result">Готово</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static "js/duel.js" %}"></script>
    {% if player.background %}
        <script type="text/javascript" src="{% static "js/background.js" %}"></script>{% endif %}
{% endblock %}

templates/bets/waiting.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Ожидание
{% endblock %}
{% block css %}
    {% if player.background %}<link rel="stylesheet" href="{% static "css/background.css" %}">{% endif %}
    <link rel="stylesheet" href="{% static 'css/waiting.css' %}">
{% endblock %}
{% block content %}
    {% if player.background %}<canvas id="background"></canvas>{% endif %}
    <div class="content">
        <div class="container-fluid">
            <div class="col-md-4 offset-md-4 anim-container mt-5">
                <div class="searching"><img src="{% static 'img/loopa.png' %}" height="64" width="64" alt="CB"></div>
            </div>
            <div class="col-md-4 offset-md-4 waiting-text text-center">Ищем противника</div>
            <div class="col-lg-2 offset-lg-5 col-sm-8 offset-sm-2 bet-info mt-2 pl-3 py-2 text-center"
                 data-time-left="{{ bet.time_left }}"
                 data-bet-id="{{ bet.id }}">
                <div id="timer">&ndash;&ndash;:&ndash;&ndash;</div><br>
                {{ bet.player.user.username }}<br>
                {{ bet.cost }} <i class="fas fa-coins"></i>
            </div>
        </div>
        <div id="connection" class="connection m-2"></div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/waiting.js' %}"></script>
    {% if player.background %}<script type="text/javascript" src="{% static "js/background.js" %}"></script>{% endif %}
{% endblock %}